from .covidamd_com import CovidAmdCom
from .covidaps_com import CovidApsCom
from .covidbaroda_com import CovidBarodaCom
from .covidbedthane_in import CovidBedThaneIn
from .covidbeed_com import CovidBeedCom
from .covidbengaluru_com import CovidBengaluruCom
from .coviddelhi_com import CovidDelhiCom
from .covidgandhinagar_com import CovidGandhiNagarCom
from .covidmp_com import CovidMPCom
from .covidnashik_com import CovidNashikCom
from .covidpune_com import CovidPuneCom
from .covidtelangana_com import CovidTelanganaCom
from .covidtnadu_com import CovidTNaduCom
from .covidwb_com import CovidWBCom
