const oxygenData = [
  {
    state: 'Andhra Pradesh',
    city: 'Vishaka',
    personName: 'Shariq Husain',
    phoneNo1: 9990431468,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  },
  {
    state: 'Tamil Nadu',
    city: 'Coimbatore',
    personName: 'Shri Hari L',
    phoneNo1: 8,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  },
  {
    state: 'Andhra Pradesh',
    city: 'Vishaka',
    personName: 'Shariq Husain',
    phoneNo1: 9990431468,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  },
  {
    state: 'Andhra Pradesh',
    city: 'Vishaka',
    personName: 'Shariq Husain',
    phoneNo1: 9990431468,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  },
  {
    state: 'Andhra Pradesh',
    city: 'Vishaka',
    personName: 'Shariq Husain',
    phoneNo1: 9990431468,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  },
  {
    state: 'Gujarat',
    city: 'London',
    personName: 'Abhi',
    phoneNo1: 9990431468,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  },
  {
    state: 'Andhra Pradesh',
    city: 'Vishaka',
    personName: 'Shariq Husain',
    phoneNo1: 9990431468,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  },
  {
    state: 'Kerala',
    city: 'Palakkad',
    personName: 'Peeyush',
    phoneNo1: 9876543210,
    phoneNo2: 9578685557,
    description: 'Jamia nagar',
    sourceName: 'Linkedin - Non government',
    sourceLink: null,
  },
  {
    state: 'Andhra Pradesh',
    city: 'Vishaka',
    personName: 'Shariq Husain',
    phoneNo1: 9990431468,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  },
  {
    state: 'Andhra Pradesh',
    city: 'Vishaka',
    personName: 'Shariq Husain',
    phoneNo1: 9990431468,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  },
  {
    state: 'Andhra Pradesh',
    city: 'Vishaka',
    personName: 'Shariq Husain',
    phoneNo1: 9990431468,
    phoneNo2: null,
    description: 'Jamia nagar',
    sourceName: 'Twitter - Non government',
    sourceLink: null,
  }
]

export default function handler(_, res) {
  res.status(200).json(oxygenData);
}
