const oxygenData = [
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      },
    {
        state: 'Andhra Pradesh',
        city: 'Vishaka',
        personName: 'Shariq Husain',
        phoneNo1: 9990431468,
        phoneNo2: null,
        description: 'Jamia nagar',
        sourceName: 'Twitter - Non government',
        sourceLink: null,
      }
]